"""Curated Scottish scenarios for the portfolio-routing reasoning engine."""

from __future__ import annotations


RULESET_VERSION = "scottish_portfolio_v1"


SEED_SITE_SCENARIOS: list[dict[str, object]] = [
    {
        "site_code": "SC-A-001",
        "site_name": "East Calder North Fields",
        "preferred_authorities": ["West Lothian", "Midlothian"],
        "min_acres": 8.0,
        "max_acres": 24.0,
        "component_target": 1,
        "workflow_status": "new",
        "nearest_settlement": "East Calder",
        "settlement_relationship": "edge_of_settlement",
        "within_settlement_boundary": False,
        "distance_to_settlement_boundary_m": 140.0,
        "planning_records": [
            {
                "record_type": "pre_app",
                "application_reference": "PRE/25/041",
                "application_outcome": "positive_pre_app",
                "application_status": "closed",
                "decision_date": "2025-06-11",
                "description": "Officer feedback accepted the settlement-edge principle subject to routine technical checks.",
                "source_dataset": "mvp_seed.planning",
                "source_record_id": "SC-A-001-preapp",
                "source_url": "internal://mvp-seed/SC-A-001/planning/preapp",
                "import_version": "mvp_seed_v2",
                "raw_payload": {
                    "has_layouts": False,
                    "has_prior_reports": False,
                    "scheme_scale": "local",
                },
            }
        ],
        "planning_context_records": [
            {
                "context_type": "emerging_ldp",
                "context_status": "emerging",
                "context_label": "Draft eastward settlement release",
                "distance_m": 0,
                "description": "Emerging plan work identifies the northern edge as a logical growth direction.",
                "source_dataset": "mvp_seed.ldp",
                "source_record_id": "SC-A-001-emerging",
                "source_url": "internal://mvp-seed/SC-A-001/context/emerging",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"allocation_code": "H-12", "authority_ref": "WL-H12"},
            },
            {
                "context_type": "nearby_growth",
                "context_status": "approved",
                "context_label": "Adjacent consented family phase",
                "distance_m": 180,
                "description": "A nearby consented phase demonstrates live growth context.",
                "source_dataset": "mvp_seed.ldp",
                "source_record_id": "SC-A-001-growth",
                "source_url": "internal://mvp-seed/SC-A-001/context/growth",
                "import_version": "mvp_seed_v2",
            },
        ],
        "constraints": [
            {
                "constraint_type": "river_flood",
                "severity": "low",
                "status": "screened",
                "description": "No material river flood effect in the seeded screen.",
                "source_dataset": "mvp_seed.flood",
                "source_record_id": "SC-A-001-river",
                "source_url": "internal://mvp-seed/SC-A-001/flood/river",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"overlap_pct": 0.0, "combined_severity": "low"},
            }
        ],
        "infrastructure_records": [
            {
                "infrastructure_type": "access",
                "burden_level": "low",
                "status": "straightforward",
                "description": "Existing frontage suggests straightforward access.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-A-001-access",
                "source_url": "internal://mvp-seed/SC-A-001/infrastructure/access",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"access_complexity": "straightforward"},
            },
            {
                "infrastructure_type": "roads",
                "burden_level": "low",
                "status": "screened",
                "description": "No major off-site roads issue surfaced at this stage.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-A-001-roads",
                "source_url": "internal://mvp-seed/SC-A-001/infrastructure/roads",
                "import_version": "mvp_seed_v2",
            },
        ],
        "control_records": [
            {
                "control_type": "ownership_fragmentation",
                "control_level": "single",
                "status": "single_owner",
                "description": "Seeded title intelligence suggests a single ownership route.",
                "source_dataset": "mvp_seed.control",
                "source_record_id": "SC-A-001-control",
                "source_url": "internal://mvp-seed/SC-A-001/control/ownership",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"fragmentation_level": "single"},
            }
        ],
        "comparables": [
            {
                "comparable_type": "new_build",
                "address": "1 Meadow View, East Calder",
                "transaction_type": "sale",
                "price_gbp": 355000,
                "price_per_sqft_gbp": 235,
                "sale_date": "2025-01-18",
                "distance_m": 820,
                "record_strength": "high",
                "description": "Recent family-house sale.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-A-001-comp-1",
                "source_url": "internal://mvp-seed/SC-A-001/market/1",
                "import_version": "mvp_seed_v2",
            },
            {
                "comparable_type": "new_build",
                "address": "4 Meadow View, East Calder",
                "transaction_type": "sale",
                "price_gbp": 348000,
                "price_per_sqft_gbp": 231,
                "sale_date": "2024-11-02",
                "distance_m": 880,
                "record_strength": "high",
                "description": "Comparable family sale.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-A-001-comp-2",
                "source_url": "internal://mvp-seed/SC-A-001/market/2",
                "import_version": "mvp_seed_v2",
            },
            {
                "comparable_type": "new_build",
                "address": "7 Meadow View, East Calder",
                "transaction_type": "sale",
                "price_gbp": 341000,
                "price_per_sqft_gbp": 227,
                "sale_date": "2024-08-24",
                "distance_m": 920,
                "record_strength": "medium",
                "description": "Third comparable supporting depth.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-A-001-comp-3",
                "source_url": "internal://mvp-seed/SC-A-001/market/3",
                "import_version": "mvp_seed_v2",
            },
            {
                "comparable_type": "new_build",
                "address": "10 Meadow View, East Calder",
                "transaction_type": "sale",
                "price_gbp": 362000,
                "price_per_sqft_gbp": 238,
                "sale_date": "2024-05-17",
                "distance_m": 980,
                "record_strength": "medium",
                "description": "Fourth comparable supporting PLC appetite.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-A-001-comp-4",
                "source_url": "internal://mvp-seed/SC-A-001/market/4",
                "import_version": "mvp_seed_v2",
            },
        ],
        "buyer_matches": [
            {
                "profile_code": "strategic_masterplan_plc",
                "fit_rating": "strong",
                "match_reason": "Clean strategic edge expansion with broad family demand.",
                "evidence_summary": "Suitable for long-term option or promotion style control.",
            },
            {
                "profile_code": "regional_family_homes",
                "fit_rating": "moderate",
                "match_reason": "Family-product values support later regional buyer demand.",
                "evidence_summary": "Secondary exit depth also exists.",
            },
        ],
    },
    {
        "site_code": "SC-B-002",
        "site_name": "Inverurie South Allocation",
        "preferred_authorities": ["Aberdeenshire", "Moray"],
        "min_acres": 10.0,
        "max_acres": 28.0,
        "component_target": 1,
        "workflow_status": "under_review",
        "nearest_settlement": "Inverurie",
        "settlement_relationship": "settlement_extension",
        "within_settlement_boundary": False,
        "distance_to_settlement_boundary_m": 60.0,
        "planning_records": [
            {
                "record_type": "pre_app",
                "application_reference": "PRE/24/118",
                "application_outcome": "positive_pre_app",
                "application_status": "closed",
                "decision_date": "2024-10-09",
                "description": "Officers indicated principle support with delivery conditions.",
                "source_dataset": "mvp_seed.planning",
                "source_record_id": "SC-B-002-preapp",
                "source_url": "internal://mvp-seed/SC-B-002/planning/preapp",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"has_layouts": True, "scheme_scale": "major"},
            }
        ],
        "planning_context_records": [
            {
                "context_type": "allocation",
                "context_status": "allocated",
                "context_label": "Adopted housing allocation",
                "distance_m": 0,
                "description": "Site is named in the adopted plan.",
                "source_dataset": "mvp_seed.ldp",
                "source_record_id": "SC-B-002-allocation",
                "source_url": "internal://mvp-seed/SC-B-002/context/allocation",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"allocation_code": "H13-GL1", "authority_ref": "ABD-H13-GL1"},
            },
            {
                "context_type": "hla_status",
                "context_status": "effective",
                "context_label": "Effective housing land",
                "distance_m": 0,
                "description": "HLA lists the site as effective.",
                "source_dataset": "mvp_seed.hla",
                "source_record_id": "SC-B-002-hla",
                "source_url": "internal://mvp-seed/SC-B-002/context/hla",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"programming_horizon": "3_to_5_years", "hla_ref": "Site 221"},
            },
        ],
        "constraints": [
            {
                "constraint_type": "surface_water_flood",
                "severity": "low",
                "status": "screened",
                "description": "Only minor edge surface water effect.",
                "source_dataset": "mvp_seed.flood",
                "source_record_id": "SC-B-002-flood",
                "source_url": "internal://mvp-seed/SC-B-002/flood/sw",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"overlap_pct": 4.0, "combined_severity": "low"},
            }
        ],
        "infrastructure_records": [
            {
                "infrastructure_type": "access",
                "burden_level": "medium",
                "status": "possible",
                "description": "Access is achievable but requires a new junction arrangement.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-B-002-access",
                "source_url": "internal://mvp-seed/SC-B-002/infrastructure/access",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"access_complexity": "possible"},
            },
            {
                "infrastructure_type": "roads",
                "burden_level": "medium",
                "status": "contribution",
                "description": "Off-site roads works and contributions are likely.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-B-002-roads",
                "source_url": "internal://mvp-seed/SC-B-002/infrastructure/roads",
                "import_version": "mvp_seed_v2",
            },
            {
                "infrastructure_type": "education",
                "burden_level": "medium",
                "status": "contribution",
                "description": "Education contribution requirement remains open.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-B-002-education",
                "source_url": "internal://mvp-seed/SC-B-002/infrastructure/education",
                "import_version": "mvp_seed_v2",
            },
        ],
        "control_records": [
            {
                "control_type": "ownership_fragmentation",
                "control_level": "multiple",
                "status": "two_owners",
                "description": "Two land interests must be aligned.",
                "source_dataset": "mvp_seed.control",
                "source_record_id": "SC-B-002-control",
                "source_url": "internal://mvp-seed/SC-B-002/control/ownership",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"fragmentation_level": "multiple"},
            }
        ],
        "comparables": [
            {
                "comparable_type": "new_build",
                "address": "2 Thainstone Avenue, Inverurie",
                "transaction_type": "sale",
                "price_gbp": 312000,
                "price_per_sqft_gbp": 212,
                "sale_date": "2025-01-09",
                "distance_m": 980,
                "record_strength": "high",
                "description": "Recent family-house comparable.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-B-002-comp-1",
                "source_url": "internal://mvp-seed/SC-B-002/market/1",
                "import_version": "mvp_seed_v2",
            },
            {
                "comparable_type": "new_build",
                "address": "6 Thainstone Avenue, Inverurie",
                "transaction_type": "sale",
                "price_gbp": 318000,
                "price_per_sqft_gbp": 214,
                "sale_date": "2024-09-13",
                "distance_m": 1040,
                "record_strength": "medium",
                "description": "Supporting comparable.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-B-002-comp-2",
                "source_url": "internal://mvp-seed/SC-B-002/market/2",
                "import_version": "mvp_seed_v2",
            },
        ],
        "buyer_matches": [
            {
                "profile_code": "regional_family_homes",
                "fit_rating": "strong",
                "match_reason": "Allocated family expansion in a solid Aberdeenshire market.",
                "evidence_summary": "Straightforward regional exit if delivery issues are managed.",
            },
            {
                "profile_code": "value_builder_scotland",
                "fit_rating": "moderate",
                "match_reason": "Could still suit value-led buyer if contributions are sensibly priced.",
                "evidence_summary": "Secondary commercial route exists.",
            },
        ],
    },
    {
        "site_code": "SC-C-003",
        "site_name": "Dunfermline Builder Re-Entry Parcel",
        "preferred_authorities": ["Fife", "West Lothian"],
        "min_acres": 6.0,
        "max_acres": 20.0,
        "component_target": 1,
        "workflow_status": "further_dd_required",
        "nearest_settlement": "Dunfermline",
        "settlement_relationship": "settlement_extension",
        "within_settlement_boundary": False,
        "distance_to_settlement_boundary_m": 90.0,
        "planning_records": [
            {
                "record_type": "application",
                "application_reference": "20/01876/PPP",
                "application_outcome": "approved",
                "application_status": "determined",
                "decision_date": "2021-07-28",
                "description": "Permission in principle granted for housing-led development.",
                "source_dataset": "mvp_seed.planning",
                "source_record_id": "SC-C-003-ppp",
                "source_url": "internal://mvp-seed/SC-C-003/planning/ppp",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"has_layouts": True, "has_prior_reports": True, "scheme_scale": "major"},
            },
            {
                "record_type": "application",
                "application_reference": "22/01411/MSC",
                "application_outcome": "withdrawn",
                "application_status": "withdrawn",
                "decision_date": "2023-03-21",
                "description": "MSC withdrawn after housebuilder sponsor insolvency.",
                "source_dataset": "mvp_seed.planning",
                "source_record_id": "SC-C-003-msc",
                "source_url": "internal://mvp-seed/SC-C-003/planning/msc",
                "import_version": "mvp_seed_v2",
                "raw_payload": {
                    "has_layouts": True,
                    "has_prior_reports": True,
                    "sponsor_failure_indicator": True,
                    "scheme_scale": "major",
                },
            },
        ],
        "planning_context_records": [
            {
                "context_type": "allocation",
                "context_status": "allocated",
                "context_label": "Adopted housing allocation",
                "distance_m": 0,
                "description": "Site remains in the plan-led growth area.",
                "source_dataset": "mvp_seed.ldp",
                "source_record_id": "SC-C-003-allocation",
                "source_url": "internal://mvp-seed/SC-C-003/context/allocation",
                "import_version": "mvp_seed_v2",
            },
            {
                "context_type": "hla_status",
                "context_status": "effective",
                "context_label": "Effective housing land",
                "distance_m": 0,
                "description": "HLA evidence remains supportive.",
                "source_dataset": "mvp_seed.hla",
                "source_record_id": "SC-C-003-hla",
                "source_url": "internal://mvp-seed/SC-C-003/context/hla",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"programming_horizon": "0_to_2_years"},
            },
        ],
        "constraints": [
            {
                "constraint_type": "site_investigation",
                "severity": "low",
                "status": "present",
                "description": "Prior ground investigation reports exist.",
                "source_dataset": "mvp_seed.bgs",
                "source_record_id": "SC-C-003-si",
                "source_url": "internal://mvp-seed/SC-C-003/bgs/si",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"si_indicator": True},
            },
            {
                "constraint_type": "surface_water_flood",
                "severity": "low",
                "status": "screened",
                "description": "Only localised edge water issue.",
                "source_dataset": "mvp_seed.flood",
                "source_record_id": "SC-C-003-flood",
                "source_url": "internal://mvp-seed/SC-C-003/flood/sw",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"overlap_pct": 6.0, "combined_severity": "low"},
            },
        ],
        "infrastructure_records": [
            {
                "infrastructure_type": "access",
                "burden_level": "medium",
                "status": "possible",
                "description": "Access requires redesign but not third-party ransom.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-C-003-access",
                "source_url": "internal://mvp-seed/SC-C-003/infrastructure/access",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"access_complexity": "possible"},
            }
        ],
        "control_records": [
            {
                "control_type": "ownership_fragmentation",
                "control_level": "single",
                "status": "single_owner",
                "description": "Control route remains straightforward.",
                "source_dataset": "mvp_seed.control",
                "source_record_id": "SC-C-003-control",
                "source_url": "internal://mvp-seed/SC-C-003/control/ownership",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"fragmentation_level": "single"},
            }
        ],
        "comparables": [
            {
                "comparable_type": "new_build",
                "address": "3 Pitfirrane Gardens, Dunfermline",
                "transaction_type": "sale",
                "price_gbp": 286000,
                "price_per_sqft_gbp": 201,
                "sale_date": "2025-02-16",
                "distance_m": 750,
                "record_strength": "high",
                "description": "Recent family sale.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-C-003-comp-1",
                "source_url": "internal://mvp-seed/SC-C-003/market/1",
                "import_version": "mvp_seed_v2",
            },
            {
                "comparable_type": "new_build",
                "address": "9 Pitfirrane Gardens, Dunfermline",
                "transaction_type": "sale",
                "price_gbp": 291000,
                "price_per_sqft_gbp": 205,
                "sale_date": "2024-10-30",
                "distance_m": 820,
                "record_strength": "medium",
                "description": "Supporting family sale.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-C-003-comp-2",
                "source_url": "internal://mvp-seed/SC-C-003/market/2",
                "import_version": "mvp_seed_v2",
            },
        ],
        "buyer_matches": [
            {
                "profile_code": "value_builder_scotland",
                "fit_rating": "strong",
                "match_reason": "Prior work and short path to value suit a re-entry buyer.",
                "evidence_summary": "Classic shorter-term re-entry profile.",
            },
            {
                "profile_code": "regional_family_homes",
                "fit_rating": "moderate",
                "match_reason": "Family housing still suits the local market once the site is restarted.",
                "evidence_summary": "Regional exit remains plausible.",
            },
        ],
    },
    {
        "site_code": "SC-D-004",
        "site_name": "Paisley Foundry Yard",
        "preferred_authorities": ["Renfrewshire", "Glasgow City"],
        "min_acres": 4.0,
        "max_acres": 14.0,
        "component_target": 1,
        "workflow_status": "under_review",
        "nearest_settlement": "Paisley",
        "settlement_relationship": "within_urban_area",
        "within_settlement_boundary": True,
        "distance_to_settlement_boundary_m": 0.0,
        "planning_records": [
            {
                "record_type": "pre_app",
                "application_reference": "PRE/23/212",
                "application_outcome": "mixed_pre_app",
                "application_status": "closed",
                "decision_date": "2024-02-14",
                "description": "Planning officers accepted redevelopment principle but required remediation and drainage evidence.",
                "source_dataset": "mvp_seed.planning",
                "source_record_id": "SC-D-004-preapp",
                "source_url": "internal://mvp-seed/SC-D-004/planning/preapp",
                "import_version": "mvp_seed_v2",
                "raw_payload": {
                    "has_layouts": True,
                    "has_prior_reports": True,
                    "refusal_themes": ["drainage", "design_density"],
                },
            }
        ],
        "planning_context_records": [
            {
                "context_type": "policy_support",
                "context_status": "supportive",
                "context_label": "Urban brownfield redevelopment area",
                "distance_m": 0,
                "description": "Urban redevelopment policy is supportive in principle.",
                "source_dataset": "mvp_seed.ldp",
                "source_record_id": "SC-D-004-policy",
                "source_url": "internal://mvp-seed/SC-D-004/context/policy",
                "import_version": "mvp_seed_v2",
            }
        ],
        "constraints": [
            {
                "constraint_type": "vdl",
                "severity": "medium",
                "status": "industrial",
                "description": "Vacant industrial yard in the local VDL evidence.",
                "source_dataset": "mvp_seed.vdl",
                "source_record_id": "SC-D-004-vdl",
                "source_url": "internal://mvp-seed/SC-D-004/vdl",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"previous_use_type": "industrial", "years_on_register": 7, "vdl_ref": "VDL-07"},
            },
            {
                "constraint_type": "site_investigation",
                "severity": "low",
                "status": "present",
                "description": "Phase 1 and intrusive reports referenced in prior work.",
                "source_dataset": "mvp_seed.bgs",
                "source_record_id": "SC-D-004-si",
                "source_url": "internal://mvp-seed/SC-D-004/bgs/si",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"si_indicator": True},
            },
            {
                "constraint_type": "surface_water_flood",
                "severity": "medium",
                "status": "screened",
                "description": "Manageable surface water effect.",
                "source_dataset": "mvp_seed.flood",
                "source_record_id": "SC-D-004-flood",
                "source_url": "internal://mvp-seed/SC-D-004/flood/sw",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"overlap_pct": 12.0, "combined_severity": "medium"},
            },
        ],
        "infrastructure_records": [
            {
                "infrastructure_type": "access",
                "burden_level": "medium",
                "status": "direct",
                "description": "Urban frontage exists but servicing needs rationalisation.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-D-004-access",
                "source_url": "internal://mvp-seed/SC-D-004/infrastructure/access",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"access_complexity": "direct"},
            },
            {
                "infrastructure_type": "drainage",
                "burden_level": "medium",
                "status": "mitigation",
                "description": "Drainage mitigation is needed but understood.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-D-004-drainage",
                "source_url": "internal://mvp-seed/SC-D-004/infrastructure/drainage",
                "import_version": "mvp_seed_v2",
            },
        ],
        "control_records": [
            {
                "control_type": "ownership_fragmentation",
                "control_level": "single",
                "status": "single_owner",
                "description": "Single-owner brownfield control route.",
                "source_dataset": "mvp_seed.control",
                "source_record_id": "SC-D-004-control",
                "source_url": "internal://mvp-seed/SC-D-004/control/ownership",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"fragmentation_level": "single"},
            }
        ],
        "comparables": [
            {
                "comparable_type": "new_build",
                "address": "12 Thread Mill Court, Paisley",
                "transaction_type": "sale",
                "price_gbp": 218000,
                "price_per_sqft_gbp": 181,
                "sale_date": "2025-01-20",
                "distance_m": 680,
                "record_strength": "medium",
                "description": "Urban apartment/townhouse comparable.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-D-004-comp-1",
                "source_url": "internal://mvp-seed/SC-D-004/market/1",
                "import_version": "mvp_seed_v2",
            },
            {
                "comparable_type": "new_build",
                "address": "4 Thread Mill Court, Paisley",
                "transaction_type": "sale",
                "price_gbp": 225000,
                "price_per_sqft_gbp": 184,
                "sale_date": "2024-08-11",
                "distance_m": 720,
                "record_strength": "medium",
                "description": "Supporting urban comparable.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-D-004-comp-2",
                "source_url": "internal://mvp-seed/SC-D-004/market/2",
                "import_version": "mvp_seed_v2",
            },
        ],
        "buyer_matches": [
            {
                "profile_code": "value_builder_scotland",
                "fit_rating": "strong",
                "match_reason": "Bounded remediation and urban brownfield profile suit value-led buyers.",
                "evidence_summary": "Technical issues appear priceable rather than open-ended.",
            }
        ],
    },
    {
        "site_code": "SC-E-005",
        "site_name": "Perth East Expansion Block",
        "preferred_authorities": ["Perth and Kinross", "Angus"],
        "min_acres": 12.0,
        "max_acres": 34.0,
        "component_target": 1,
        "workflow_status": "under_review",
        "nearest_settlement": "Perth",
        "settlement_relationship": "settlement_extension",
        "within_settlement_boundary": False,
        "distance_to_settlement_boundary_m": 110.0,
        "planning_records": [
            {
                "record_type": "pre_app",
                "application_reference": "PRE/24/302",
                "application_outcome": "positive_pre_app",
                "application_status": "closed",
                "decision_date": "2024-12-02",
                "description": "Planning officers agreed the principle subject to servicing strategy.",
                "source_dataset": "mvp_seed.planning",
                "source_record_id": "SC-E-005-preapp",
                "source_url": "internal://mvp-seed/SC-E-005/planning/preapp",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"has_layouts": True},
            }
        ],
        "planning_context_records": [
            {
                "context_type": "allocation",
                "context_status": "allocated",
                "context_label": "Strategic expansion allocation",
                "distance_m": 0,
                "description": "Adopted plan supports the principle of housing.",
                "source_dataset": "mvp_seed.ldp",
                "source_record_id": "SC-E-005-allocation",
                "source_url": "internal://mvp-seed/SC-E-005/context/allocation",
                "import_version": "mvp_seed_v2",
            },
            {
                "context_type": "hla_constraint",
                "context_status": "constrained",
                "context_label": "Infrastructure constrained",
                "distance_m": 0,
                "description": "HLA notes roads and wastewater constraints.",
                "source_dataset": "mvp_seed.hla",
                "source_record_id": "SC-E-005-hla",
                "source_url": "internal://mvp-seed/SC-E-005/context/hla",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"programming_horizon": "3_to_5_years", "constraint_reasons": ["roads", "wastewater"]},
            },
        ],
        "constraints": [
            {
                "constraint_type": "river_flood",
                "severity": "low",
                "status": "screened",
                "description": "Flood is not the lead issue.",
                "source_dataset": "mvp_seed.flood",
                "source_record_id": "SC-E-005-flood",
                "source_url": "internal://mvp-seed/SC-E-005/flood/river",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"overlap_pct": 2.0, "combined_severity": "low"},
            }
        ],
        "infrastructure_records": [
            {
                "infrastructure_type": "access",
                "burden_level": "high",
                "status": "possible",
                "description": "Primary access solution needs major junction work.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-E-005-access",
                "source_url": "internal://mvp-seed/SC-E-005/infrastructure/access",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"access_complexity": "possible"},
            },
            {
                "infrastructure_type": "roads",
                "burden_level": "critical",
                "status": "major_enabling",
                "description": "Off-site roads package is the dominant blocker.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-E-005-roads",
                "source_url": "internal://mvp-seed/SC-E-005/infrastructure/roads",
                "import_version": "mvp_seed_v2",
            },
            {
                "infrastructure_type": "wastewater",
                "burden_level": "critical",
                "status": "network_capacity",
                "description": "Wastewater reinforcement is required before delivery.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-E-005-wastewater",
                "source_url": "internal://mvp-seed/SC-E-005/infrastructure/wastewater",
                "import_version": "mvp_seed_v2",
            },
        ],
        "control_records": [
            {
                "control_type": "ownership_fragmentation",
                "control_level": "multiple",
                "status": "two_owners",
                "description": "Two ownership interests exist, but not fatally.",
                "source_dataset": "mvp_seed.control",
                "source_record_id": "SC-E-005-control",
                "source_url": "internal://mvp-seed/SC-E-005/control/ownership",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"fragmentation_level": "multiple"},
            }
        ],
        "comparables": [
            {
                "comparable_type": "new_build",
                "address": "1 Kinnoull Rise, Perth",
                "transaction_type": "sale",
                "price_gbp": 329000,
                "price_per_sqft_gbp": 221,
                "sale_date": "2025-01-12",
                "distance_m": 900,
                "record_strength": "high",
                "description": "Strong family comparable.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-E-005-comp-1",
                "source_url": "internal://mvp-seed/SC-E-005/market/1",
                "import_version": "mvp_seed_v2",
            },
            {
                "comparable_type": "new_build",
                "address": "5 Kinnoull Rise, Perth",
                "transaction_type": "sale",
                "price_gbp": 336000,
                "price_per_sqft_gbp": 224,
                "sale_date": "2024-09-29",
                "distance_m": 960,
                "record_strength": "medium",
                "description": "Supporting comparable.",
                "source_dataset": "mvp_seed.market",
                "source_record_id": "SC-E-005-comp-2",
                "source_url": "internal://mvp-seed/SC-E-005/market/2",
                "import_version": "mvp_seed_v2",
            },
        ],
        "buyer_matches": [
            {
                "profile_code": "strategic_masterplan_plc",
                "fit_rating": "strong",
                "match_reason": "The site is attractive in principle if infrastructure can be unlocked.",
                "evidence_summary": "Strong buyer logic, but enabling burden dominates.",
            },
            {
                "profile_code": "regional_family_homes",
                "fit_rating": "moderate",
                "match_reason": "Regional buyers may want it later once servicing is solved.",
                "evidence_summary": "Exit depth is real if infrastructure clears.",
            },
        ],
    },
    {
        "site_code": "SC-F-006",
        "site_name": "Rural Falkirk West Fringe",
        "preferred_authorities": ["Falkirk", "Stirling"],
        "min_acres": 8.0,
        "max_acres": 22.0,
        "component_target": 1,
        "workflow_status": "rejected",
        "nearest_settlement": "Falkirk",
        "settlement_relationship": "open_countryside",
        "within_settlement_boundary": False,
        "distance_to_settlement_boundary_m": 1450.0,
        "planning_records": [
            {
                "record_type": "application",
                "application_reference": "23/00718/FUL",
                "application_outcome": "refused",
                "application_status": "determined",
                "decision_date": "2024-01-25",
                "description": "Refused on planning principle as sporadic countryside development with no settlement justification.",
                "source_dataset": "mvp_seed.planning",
                "source_record_id": "SC-F-006-refusal",
                "source_url": "internal://mvp-seed/SC-F-006/planning/refusal",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"refusal_themes": ["planning_principle"]},
            }
        ],
        "planning_context_records": [
            {
                "context_type": "allocation",
                "context_status": "unallocated",
                "context_label": "No allocation support",
                "distance_m": 0,
                "description": "No adopted or emerging policy support.",
                "source_dataset": "mvp_seed.ldp",
                "source_record_id": "SC-F-006-allocation",
                "source_url": "internal://mvp-seed/SC-F-006/context/allocation",
                "import_version": "mvp_seed_v2",
            }
        ],
        "constraints": [
            {
                "constraint_type": "surface_water_flood",
                "severity": "high",
                "status": "screened",
                "description": "Substantial flood and low-lying drainage exposure.",
                "source_dataset": "mvp_seed.flood",
                "source_record_id": "SC-F-006-flood",
                "source_url": "internal://mvp-seed/SC-F-006/flood/sw",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"overlap_pct": 42.0, "combined_severity": "high"},
            }
        ],
        "infrastructure_records": [
            {
                "infrastructure_type": "access",
                "burden_level": "critical",
                "status": "problematic",
                "description": "No credible frontage without third-party land.",
                "source_dataset": "mvp_seed.infrastructure",
                "source_record_id": "SC-F-006-access",
                "source_url": "internal://mvp-seed/SC-F-006/infrastructure/access",
                "import_version": "mvp_seed_v2",
                "raw_payload": {"access_complexity": "problematic"},
            }
        ],
        "control_records": [
            {
                "control_type": "legal_issue",
                "control_level": "critical",
                "status": "ransom_strip",
                "description": "Access control mismatch and ransom strip risk.",
                "source_dataset": "mvp_seed.control",
                "source_record_id": "SC-F-006-control",
                "source_url": "internal://mvp-seed/SC-F-006/control/legal",
                "import_version": "mvp_seed_v2",
            }
        ],
        "comparables": [],
        "buyer_matches": [],
    },
]
