alter table public.sites enable row level security;
alter table public.site_locations enable row level security;
alter table public.site_parcels enable row level security;
alter table public.site_geometry_components enable row level security;
alter table public.planning_records enable row level security;
alter table public.planning_context_records enable row level security;
alter table public.site_constraints enable row level security;
alter table public.comparable_market_records enable row level security;
alter table public.buyer_profiles enable row level security;
alter table public.site_buyer_matches enable row level security;
alter table public.site_analysis_runs enable row level security;
alter table public.site_signals enable row level security;
alter table public.site_interpretations enable row level security;
alter table public.evidence_references enable row level security;
alter table public.site_signal_evidence enable row level security;
alter table public.site_interpretation_evidence enable row level security;
alter table public.site_review_status_history enable row level security;
alter table public.site_refresh_queue enable row level security;

revoke all on table public.sites from anon, authenticated;
revoke all on table public.site_locations from anon, authenticated;
revoke all on table public.site_parcels from anon, authenticated;
revoke all on table public.site_geometry_components from anon, authenticated;
revoke all on table public.planning_records from anon, authenticated;
revoke all on table public.planning_context_records from anon, authenticated;
revoke all on table public.site_constraints from anon, authenticated;
revoke all on table public.comparable_market_records from anon, authenticated;
revoke all on table public.buyer_profiles from anon, authenticated;
revoke all on table public.site_buyer_matches from anon, authenticated;
revoke all on table public.site_analysis_runs from anon, authenticated;
revoke all on table public.site_signals from anon, authenticated;
revoke all on table public.site_interpretations from anon, authenticated;
revoke all on table public.evidence_references from anon, authenticated;
revoke all on table public.site_signal_evidence from anon, authenticated;
revoke all on table public.site_interpretation_evidence from anon, authenticated;
revoke all on table public.site_review_status_history from anon, authenticated;
revoke all on table public.site_refresh_queue from anon, authenticated;

revoke all on table analytics.site_search_cache from anon, authenticated;
revoke all on table analytics.v_site_current_analysis_runs from anon, authenticated;
revoke all on table analytics.v_site_current_signals from anon, authenticated;
revoke all on table analytics.v_site_current_interpretations from anon, authenticated;
revoke all on table analytics.v_site_fact_summary from anon, authenticated;
revoke all on table analytics.v_site_search_summary from anon, authenticated;
