alter table public.site_reviews enable row level security;
alter table public.site_review_checks enable row level security;
alter table public.site_appraisal_assumption_sets enable row level security;
alter table public.site_appraisal_assumptions enable row level security;
alter table public.site_appraisal_runs enable row level security;
alter table public.site_appraisal_scenarios enable row level security;
alter table public.site_appraisal_summaries enable row level security;
alter table public.buyer_entities enable row level security;
alter table public.buyer_region_rules enable row level security;
alter table public.buyer_residential_profiles enable row level security;
alter table public.buyer_evidence enable row level security;
alter table public.buyer_contacts enable row level security;
alter table public.site_buyer_match_evidence enable row level security;
alter table public.investor_entities enable row level security;
alter table public.investor_evidence enable row level security;
alter table public.investor_source_systems enable row level security;
alter table public.site_investor_matches enable row level security;
alter table public.site_investor_match_evidence enable row level security;
alter table public.site_strategy_recommendations enable row level security;

revoke all on table public.site_reviews from anon, authenticated;
revoke all on table public.site_review_checks from anon, authenticated;
revoke all on table public.site_appraisal_assumption_sets from anon, authenticated;
revoke all on table public.site_appraisal_assumptions from anon, authenticated;
revoke all on table public.site_appraisal_runs from anon, authenticated;
revoke all on table public.site_appraisal_scenarios from anon, authenticated;
revoke all on table public.site_appraisal_summaries from anon, authenticated;
revoke all on table public.buyer_entities from anon, authenticated;
revoke all on table public.buyer_region_rules from anon, authenticated;
revoke all on table public.buyer_residential_profiles from anon, authenticated;
revoke all on table public.buyer_evidence from anon, authenticated;
revoke all on table public.buyer_contacts from anon, authenticated;
revoke all on table public.site_buyer_match_evidence from anon, authenticated;
revoke all on table public.investor_entities from anon, authenticated;
revoke all on table public.investor_evidence from anon, authenticated;
revoke all on table public.investor_source_systems from anon, authenticated;
revoke all on table public.site_investor_matches from anon, authenticated;
revoke all on table public.site_investor_match_evidence from anon, authenticated;
revoke all on table public.site_strategy_recommendations from anon, authenticated;

revoke all on table analytics.v_site_current_reviews from anon, authenticated;
revoke all on table analytics.v_site_current_appraisal_runs from anon, authenticated;
revoke all on table analytics.v_site_current_appraisal_summaries from anon, authenticated;
revoke all on table analytics.v_site_current_buyer_matches from anon, authenticated;
revoke all on table analytics.v_site_current_investor_matches from anon, authenticated;
revoke all on table analytics.v_site_current_strategy_recommendations from anon, authenticated;
