create table if not exists public.site_spatial_links (
    id uuid primary key default gen_random_uuid(),
    site_id text not null,
    site_location_id text not null,
    linked_record_table text not null,
    linked_record_id text not null,
    linked_object_type text not null,
    link_role text not null,
    link_method text not null check (link_method in ('intersects', 'contains', 'within', 'nearest', 'manual', 'derived')),
    link_distance_m numeric,
    overlap_area_sqm numeric,
    overlap_pct_of_site numeric,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (link_distance_m is null or link_distance_m >= 0),
    check (overlap_area_sqm is null or overlap_area_sqm >= 0),
    check (overlap_pct_of_site is null or overlap_pct_of_site between 0 and 100)
);

create table if not exists public.site_title_validation (
    id uuid primary key default gen_random_uuid(),
    site_id text not null,
    site_location_id text not null,
    title_number text not null,
    normalized_title_number text not null,
    matched_title_number text,
    validation_status text not null check (validation_status in ('matched', 'probable', 'unmatched', 'manual_review', 'rejected')),
    validation_method text not null check (validation_method in ('spatial_intersection', 'documentary', 'manual', 'imported', 'derived')),
    confidence numeric,
    title_source text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (confidence is null or (confidence >= 0 and confidence <= 1))
);

create table if not exists public.constraint_layer_registry (
    id uuid primary key default gen_random_uuid(),
    layer_key text not null unique,
    layer_name text not null,
    source_name text not null,
    source_family text not null default 'constraint',
    constraint_group text not null,
    constraint_type text not null,
    geometry_type text,
    measurement_mode text not null check (measurement_mode in ('intersection', 'distance', 'intersection_and_distance')),
    buffer_distance_m numeric not null default 0,
    is_active boolean not null default true,
    source_registry_id uuid references public.source_registry(id),
    legacy_site_constraints_key text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (buffer_distance_m >= 0)
);

create table if not exists public.constraint_source_features (
    id uuid primary key default gen_random_uuid(),
    constraint_layer_id uuid not null references public.constraint_layer_registry(id) on delete cascade,
    source_feature_key text not null,
    feature_name text,
    source_reference text,
    authority_name text,
    severity_label text,
    source_url text,
    effective_from date,
    effective_to date,
    geometry geometry(Geometry, 27700) not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.site_constraint_measurements (
    id uuid primary key default gen_random_uuid(),
    site_id text not null,
    site_location_id text not null,
    constraint_layer_id uuid not null references public.constraint_layer_registry(id) on delete cascade,
    constraint_feature_id uuid not null references public.constraint_source_features(id) on delete cascade,
    measurement_source text not null default 'site_location_geometry',
    intersects boolean not null default false,
    within_buffer boolean not null default false,
    site_inside_feature boolean not null default false,
    feature_inside_site boolean not null default false,
    overlap_area_sqm numeric not null default 0,
    overlap_pct_of_site numeric not null default 0,
    overlap_pct_of_feature numeric not null default 0,
    nearest_distance_m numeric,
    buffer_distance_m numeric not null default 0,
    measured_at timestamptz not null default now(),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (overlap_area_sqm >= 0),
    check (overlap_pct_of_site between 0 and 100),
    check (overlap_pct_of_feature between 0 and 100),
    check (nearest_distance_m is null or nearest_distance_m >= 0),
    check (buffer_distance_m >= 0)
);

create table if not exists public.site_constraint_group_summaries (
    id uuid primary key default gen_random_uuid(),
    site_id text not null,
    site_location_id text not null,
    constraint_layer_id uuid not null references public.constraint_layer_registry(id) on delete cascade,
    constraint_group text not null,
    summary_scope text not null default 'site_location_geometry',
    intersecting_feature_count integer not null default 0,
    buffered_feature_count integer not null default 0,
    total_overlap_area_sqm numeric not null default 0,
    max_overlap_pct_of_site numeric not null default 0,
    min_distance_m numeric,
    nearest_feature_id uuid references public.constraint_source_features(id) on delete set null,
    nearest_feature_name text,
    measured_at timestamptz not null default now(),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (intersecting_feature_count >= 0),
    check (buffered_feature_count >= 0),
    check (total_overlap_area_sqm >= 0),
    check (max_overlap_pct_of_site between 0 and 100),
    check (min_distance_m is null or min_distance_m >= 0)
);

create table if not exists public.site_commercial_friction_facts (
    id uuid primary key default gen_random_uuid(),
    site_id text not null,
    site_location_id text not null,
    constraint_group text not null,
    constraint_layer_id uuid not null references public.constraint_layer_registry(id) on delete cascade,
    fact_key text not null,
    fact_label text not null,
    fact_value_text text,
    fact_value_numeric numeric,
    fact_unit text,
    fact_basis text not null,
    source_measurement_id uuid references public.site_constraint_measurements(id) on delete set null,
    source_summary_id uuid references public.site_constraint_group_summaries(id) on delete set null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
