create table if not exists public.bgs_boreholes_raw (
    id bigserial primary key,
    ingest_run_id uuid not null references public.ingest_runs(id) on delete cascade,
    source_row_number bigint not null,
    source_archive_name text not null,
    source_file_name text not null,
    source_snapshot_date date not null,
    source_dataset_key text not null default 'bgs_single_onshore_borehole_index',
    source_dataset_name text not null default 'BGS Single Onshore Borehole Index',
    qs text,
    numb bigint,
    bsuff text,
    regno text,
    rt text,
    grid_refer text,
    easting text,
    northing text,
    x numeric,
    y numeric,
    confidenti text,
    strtheight numeric,
    name text,
    length numeric,
    bgs_id bigint,
    date_known integer,
    date_k_typ text,
    date_enter date,
    ags_log_ur text,
    raw_record jsonb not null default '{}'::jsonb,
    geom geometry(point, 27700),
    imported_at timestamptz not null default now(),
    unique (ingest_run_id, source_row_number)
);

create table if not exists public.bgs_boreholes (
    bgs_id bigint primary key,
    regno text,
    qs text,
    numb integer,
    bsuff text,
    rt text,
    grid_reference text,
    source_easting_raw text,
    source_northing_raw text,
    easting numeric,
    northing numeric,
    geom geometry(point, 27700),
    geom_wgs84 geometry(point, 4326),
    confidentiality_code text,
    is_confidential boolean not null default false,
    start_height_raw text,
    start_height_m numeric,
    name_original text,
    name_normalised text,
    name_tokens text[] not null default '{}'::text[],
    depth_raw text,
    depth_m numeric,
    depth_status text not null default 'missing'
        check (depth_status in ('missing', 'zero', 'positive', 'invalid')),
    ags_log_url text,
    has_ags_log boolean not null default false,
    date_known_raw text,
    date_known_year integer,
    date_known_type text,
    date_entered date,
    is_scotland boolean not null default false,
    scotland_authority_name text,
    source_dataset_key text not null default 'bgs_single_onshore_borehole_index',
    source_dataset_name text not null default 'BGS Single Onshore Borehole Index',
    source_archive_name text,
    source_file_name text,
    source_snapshot_date date not null,
    source_ingest_run_id uuid not null references public.ingest_runs(id) on delete restrict,
    source_row_number bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (date_known_year is null or date_known_year between 1000 and 2100)
);
