revoke all on schema landintel from public, anon, authenticated;

alter table if exists landintel.canonical_sites enable row level security;
alter table if exists landintel.planning_application_records enable row level security;
alter table if exists landintel.hla_site_records enable row level security;
alter table if exists landintel.ldp_site_records enable row level security;
alter table if exists landintel.settlement_boundary_records enable row level security;
alter table if exists landintel.bgs_records enable row level security;
alter table if exists landintel.flood_records enable row level security;
alter table if exists landintel.ela_site_records enable row level security;
alter table if exists landintel.vdl_site_records enable row level security;
alter table if exists landintel.site_source_links enable row level security;
alter table if exists landintel.site_reference_aliases enable row level security;
alter table if exists landintel.evidence_references enable row level security;
alter table if exists landintel.source_reconcile_state enable row level security;
alter table if exists landintel.source_reconcile_queue enable row level security;
alter table if exists landintel.site_signals enable row level security;
alter table if exists landintel.site_assessments enable row level security;
alter table if exists landintel.canonical_site_refresh_queue enable row level security;
alter table if exists landintel.site_review_events enable row level security;
alter table if exists landintel.site_manual_overrides enable row level security;
alter table if exists landintel.site_change_events enable row level security;
alter table if exists landintel.site_geometry_diagnostics enable row level security;

alter table if exists public.site_spatial_links enable row level security;
alter table if exists public.site_title_validation enable row level security;
alter table if exists public.constraint_layer_registry enable row level security;
alter table if exists public.constraint_source_features enable row level security;
alter table if exists public.site_constraint_measurements enable row level security;
alter table if exists public.site_constraint_group_summaries enable row level security;
alter table if exists public.site_commercial_friction_facts enable row level security;

revoke all on table landintel.canonical_sites from anon, authenticated;
revoke all on table landintel.planning_application_records from anon, authenticated;
revoke all on table landintel.hla_site_records from anon, authenticated;
revoke all on table landintel.ldp_site_records from anon, authenticated;
revoke all on table landintel.settlement_boundary_records from anon, authenticated;
revoke all on table landintel.bgs_records from anon, authenticated;
revoke all on table landintel.flood_records from anon, authenticated;
revoke all on table landintel.ela_site_records from anon, authenticated;
revoke all on table landintel.vdl_site_records from anon, authenticated;
revoke all on table landintel.site_source_links from anon, authenticated;
revoke all on table landintel.site_reference_aliases from anon, authenticated;
revoke all on table landintel.evidence_references from anon, authenticated;
revoke all on table landintel.source_reconcile_state from anon, authenticated;
revoke all on table landintel.source_reconcile_queue from anon, authenticated;
revoke all on table landintel.site_signals from anon, authenticated;
revoke all on table landintel.site_assessments from anon, authenticated;
revoke all on table landintel.canonical_site_refresh_queue from anon, authenticated;
revoke all on table landintel.site_review_events from anon, authenticated;
revoke all on table landintel.site_manual_overrides from anon, authenticated;
revoke all on table landintel.site_change_events from anon, authenticated;
revoke all on table landintel.site_geometry_diagnostics from anon, authenticated;

revoke all on table public.site_spatial_links from anon, authenticated;
revoke all on table public.site_title_validation from anon, authenticated;
revoke all on table public.constraint_layer_registry from anon, authenticated;
revoke all on table public.constraint_source_features from anon, authenticated;
revoke all on table public.site_constraint_measurements from anon, authenticated;
revoke all on table public.site_constraint_group_summaries from anon, authenticated;
revoke all on table public.site_commercial_friction_facts from anon, authenticated;

revoke all on table analytics.v_constraints_tab_measurements from anon, authenticated;
revoke all on table analytics.v_constraints_tab_group_summaries from anon, authenticated;
revoke all on table analytics.v_constraints_tab_commercial_friction from anon, authenticated;
revoke all on table analytics.v_constraints_tab_overview from anon, authenticated;
revoke all on table analytics.v_live_site_title from anon, authenticated;
revoke all on table analytics.v_live_site_constraints from anon, authenticated;
revoke all on table analytics.v_live_site_assessment from anon, authenticated;
revoke all on table analytics.v_live_site_review_state from anon, authenticated;
revoke all on table analytics.v_live_site_change_log from anon, authenticated;
revoke all on table analytics.v_live_priority_alerts from anon, authenticated;
revoke all on table analytics.v_live_site_summary_base from anon, authenticated;
revoke all on table analytics.v_live_site_summary from anon, authenticated;
revoke all on table analytics.v_live_site_readiness from anon, authenticated;
revoke all on table analytics.v_live_site_sources from anon, authenticated;
revoke all on table analytics.v_live_opportunity_queue from anon, authenticated;

revoke all on function public.constraints_site_anchor() from public, anon, authenticated;
revoke all on function landintel.enqueue_canonical_site_refresh(uuid, text, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function landintel.record_site_change_event(uuid, text, text, text, text, text, text, boolean, jsonb, boolean) from public, anon, authenticated;
revoke all on function landintel.record_planning_change_event(uuid, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function landintel.record_policy_change_event(uuid, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function landintel.record_title_review_event(uuid, text, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function landintel.publish_reconciled_planning_links(integer) from public, anon, authenticated;
