target_councils:
  - Glasgow City
  - City of Edinburgh
  - North Lanarkshire
  - South Lanarkshire
  - East Renfrewshire
  - Renfrewshire
  - Inverclyde
  - West Dunbartonshire
  - East Dunbartonshire
  - Falkirk
  - West Lothian
  - Midlothian
  - East Lothian
  - Clackmannanshire
  - Stirling
  - Perth and Kinross
  - Dundee City
  - North Ayrshire
  - East Ayrshire
  - South Ayrshire
